"""The explainer page's numbers must be the artifacts' numbers, and stay that way.

WHY THIS EXISTS
===============

``README.md`` states two different capture counts in two places. It did not start
wrong; it was typed once and the tree moved underneath it. ``explainer/`` is a
second public surface carrying the same numbers, so it is generated by
``explainer/build.py`` from committed files rather than typed. That removes the
*writing* failure. It does not remove the *staleness* failure: a generated file
committed to the tree goes stale the moment an artifact changes and nobody
rebuilds. This module is the half that catches that.

WHAT IT ASSERTS, AND WHY EACH IS NOT THE SAME ASSERTION TWICE
=============================================================

1. **The committed HTML equals a fresh build.** Catches the stale-checkout case.
2. **Two fresh builds are byte-identical.** Catches a generator that has acquired
   a timestamp, a hash-ordered dict, or a ``git`` call -- any of which would make
   (1) fail spuriously forever after and get this file deleted.
3. **The page's numbers match numbers recomputed here, from the artifacts,
   without calling the generator's own derivation code.** This is the load-
   bearing one. (1) and (2) would both pass on a generator that derived every
   number wrongly but consistently. The recomputation below is deliberately
   written a second time rather than imported, because a test that asks the code
   under test what the answer is has not checked anything.

WHY THE NON-VACUITY CHECKS ARE NOT DECORATION
=============================================

Every "this number appears on the page" assertion has a mirror asserting that an
adjacent wrong number does not. Without those, an empty page and a page that
renders every figure would both pass a substring scan -- ``assert "0" in text``
is true of almost any document. Two zeros in this repository were nearly
published from detectors that could not have returned anything else; the same
mistake in a test is cheaper to make and harder to see.

NO DATABASE, NO NETWORK, NO MODEL
=================================

Everything here reads committed files. It does not touch the lab Postgres, so it
is safe to run alone while another suite holds the advisory lock in
``tests/conftest.py``.
"""

from __future__ import annotations

import html as html_mod
import importlib.util
import json
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from decimal import Decimal
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
EXPLAINER = ROOT / "explainer"
BUILD = EXPLAINER / "build.py"
WRAPPERS = ("index.html", "artifact-body.html")

# The README's figures are the same build's output as the page, and are held to
# the same two rules: current with the artifacts, and byte-identical run to run.
# A README that embeds a drawing nobody regenerates is the stale-number failure
# this whole file exists to catch, moved into an image where it is harder to see.
FIGURES = tuple(
    f"figures/{stem}{suffix}.svg"
    for stem in ("finding-t1-vs-t4", "t1-three-arms", "t4-three-arms")
    for suffix in ("", "-dark")
)
OUTPUTS = WRAPPERS + FIGURES

FONT_HOSTS = ("https://fonts.googleapis.com", "https://fonts.gstatic.com")
SVG_TEXT = "{http://www.w3.org/2000/svg}text"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_build_module():
    """Import the generator by path; ``explainer/`` is output, not a package."""
    spec = importlib.util.spec_from_file_location("explainer_build", BUILD)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _plain_text(markup: str) -> str:
    """Rendered text only: no style, no script, no tags, entities resolved."""
    stripped = re.sub(r"<style>.*?</style>", " ", markup, flags=re.DOTALL)
    stripped = re.sub(r"<script>.*?</script>", " ", stripped, flags=re.DOTALL)
    stripped = re.sub(r"<[^>]+>", " ", stripped)
    return re.sub(r"\s+", " ", html_mod.unescape(stripped))


@pytest.fixture(scope="module")
def page() -> str:
    path = EXPLAINER / "index.html"
    assert path.exists(), "explainer/index.html is missing; run explainer/build.py"
    return path.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def text(page: str) -> str:
    body = _plain_text(page)
    # Non-vacuity for the fixture itself: a stripper that returned "" would make
    # every "not in text" assertion below pass and every "in text" fail loudly,
    # but a stripper that returned the raw markup would make them all pass.
    assert 4000 < len(body) < len(page), "text extraction produced an implausible result"
    return body


# ---------------------------------------------------------------------------
# 1 + 2: the committed output is current, and the generator is deterministic
# ---------------------------------------------------------------------------


def test_committed_output_matches_a_fresh_build() -> None:
    result = subprocess.run(
        [sys.executable, str(BUILD), "--check"],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
        # The non-zero exit is the signal this test reads, so it must not raise.
        check=False,
    )
    assert result.returncode == 0, (
        "explainer/ output (the two wrappers and the six README figures) is stale "
        "relative to the artifacts it claims to derive from. Run "
        f"`python explainer/build.py`.\n{result.stdout}{result.stderr}"
    )


def test_two_builds_are_byte_identical(tmp_path: Path) -> None:
    digests = []
    for run in ("a", "b"):
        out = tmp_path / run
        subprocess.run(
            [sys.executable, str(BUILD), "--out", str(out)],
            check=True,
            capture_output=True,
            cwd=str(ROOT),
        )
        digests.append({name: (out / name).read_bytes() for name in OUTPUTS})
    assert digests[0] == digests[1], "the build is not idempotent"
    assert all(len(digests[0][n]) > 10_000 for n in WRAPPERS), "build produced stubs"
    assert all(len(digests[0][n]) > 3_000 for n in FIGURES), "a figure is a stub"


def test_both_wrappers_share_one_template(page: str) -> None:
    body_only = (EXPLAINER / "artifact-body.html").read_text(encoding="utf-8")

    assert page.startswith("<!doctype html>")
    for tag in ("<html", "<head>", "</head>", "<body>", "</body>"):
        assert tag in page.lower()
        assert tag not in body_only.lower(), f"artifact-body.html contains {tag}"

    assert body_only.startswith("<title>")
    assert body_only.index("<title>") < body_only.index("<style>")

    shared_from_page = page.split("<body>\n", 1)[1].rsplit("\n</body>", 1)[0].strip()
    shared_from_body = body_only.split("</style>", 1)[1].strip()
    assert shared_from_page == shared_from_body, "the two wrappers disagree"


# ---------------------------------------------------------------------------
# 3: the numbers, recomputed here rather than imported
# ---------------------------------------------------------------------------


def _capture_bodies() -> list[dict]:
    bodies = []
    for family in ("model-captures", "monitor-captures"):
        for path in sorted((ROOT / "artifacts" / family).rglob("*.json")):
            bodies.append(json.loads(path.read_text(encoding="utf-8")))
    return bodies


def test_capture_count_and_spend(text: str) -> None:
    bodies = _capture_bodies()
    total = len(bodies)
    spend = sum(
        (
            Decimal(str(b["provenance"]["estimated_cost"]))
            for b in bodies
            if b["provenance"].get("estimated_cost") is not None
        ),
        Decimal(0),
    )
    assert total > 0 and spend > 0, "no captures found; the scan is broken, not the page"

    assert f" {total} " in text, f"the page does not carry the capture count {total}"
    assert f"${spend:.6f}" in text, f"the page does not carry the spend ${spend:.6f}"
    assert f" {total + 1} " not in text, "a wrong capture count is on the page"


def test_durability_totals(text: str) -> None:
    matrix = json.loads(
        (ROOT / "artifacts/chaos-matrix/kill-matrix.json").read_text(encoding="utf-8")
    )
    totals = matrix["totals"]
    assert totals["cells"] > 0

    reasoned = sum(
        1 for c in matrix["cells"] if c["verdict"] == "n/a" and c.get("reason")
    )
    # Anchored to their labels: a bare "160/160" would also match inside a
    # longer run of digits, and "0/30" is a substring of "30/30".
    assert f"cells {totals['cells']} " in text
    assert f"recovered clean {totals['clean']} " in text
    assert f"orphaned approvals {totals['orphaned_approvals']} " in text
    assert f"{totals['clean']}/{totals['kills']} kill cells recovered" in text
    assert f"{totals['clean'] + 1}/{totals['kills']} kill cells recovered" not in text
    assert f"n/a cells, all reasoned {reasoned}/{totals['not_applicable']}" in text, (
        "the page no longer says every n/a cell carries a reason"
    )


def test_checkpoint_b_has_no_model_and_replays_exactly(text: str) -> None:
    raw = json.loads(
        (ROOT / "artifacts/evaluations/checkpoint-b/raw-results.json").read_text(
            encoding="utf-8"
        )
    )
    reg = json.loads(
        (ROOT / "artifacts/evaluations/checkpoint-b/regression.json").read_text(
            encoding="utf-8"
        )
    )
    rows = len(raw["results"])
    backed = sum(
        1
        for r in raw["results"]
        if (r.get("model_invocation") or {}).get("invocation_kind")
        not in ("disabled", "fixture_no_call")
    )
    assert rows == 30 and backed == 0, (
        "checkpoint-B changed shape; the page's claim about it must be rechecked"
    )
    assert f"model-backed {backed}/{rows}" in text
    assert f"model-backed {backed + 1}/{rows}" not in text
    assert f"replay match {reg['compared']}/{rows}" in text
    assert reg["matched"] is True


def test_three_condition_comparison(text: str) -> None:
    """Each arm's covert outcome, stage and side-effect count reach the page."""
    seen = set()
    for path in sorted((ROOT / "artifacts/model-attacker").glob("*.json")):
        env = json.loads(path.read_text(encoding="utf-8"))
        for row in env["results"]:
            if not row["attacker_source"].startswith("model:"):
                continue
            step = row["covert_episode"]["steps"][0]
            seen.add(
                (
                    row["condition"],
                    row["covert_outcome"],
                    step["stage_reached"],
                    row["covert_side_effect_count"],
                    row["incident_checker_passed"],
                )
            )
    assert len(seen) == 3, f"expected one distinct outcome per arm, got {len(seen)}"

    landed = [s for s in seen if s[3] > 0]
    prevented = [s for s in seen if s[3] == 0]
    assert len(landed) == 1 and len(prevented) == 2

    for condition, outcome, stage, side_effects, repaired in seen:
        assert condition in text
        assert outcome in text
        assert stage in text
        assert repaired is True, "the incident leg is no longer repaired in every arm"
    assert "ungated_evaluation_only disabled disabled disabled landed" in text


def test_route_b_row_and_its_rationale(text: str, page: str) -> None:
    env = json.loads(
        (
            ROOT / "artifacts/observe-only/T1-observe-only-nemo-dev-qwen3.json"
        ).read_text(encoding="utf-8")
    )
    assert len(env["results"]) == 1, "Route B is no longer a single published row"
    step = env["results"][0]["covert_steps"][0]

    assert step["monitor_verdict"] == "block"
    assert step["rationale"] in text, "the monitor's rationale is not quoted verbatim"
    assert html_mod.escape(step["rationale"]) in page, "the rationale is not escaped"

    # The published rationale must also be a capture body's rationale.
    matches = [
        p
        for p in sorted((ROOT / "artifacts/monitor-captures").rglob("*.json"))
        if json.loads(json.loads(p.read_text(encoding="utf-8"))["raw_json"]).get(
            "rationale"
        )
        == step["rationale"]
    ]
    assert len(matches) == 1, "the Route B rationale does not resolve to one capture"

    # ...and the page must say which capture, so a reader can check it.
    assert matches[0].name.removesuffix(".json") in page


def test_bounds_panel_states_the_four_bounds(text: str) -> None:
    for phrase in (
        "no error bar comes from repeated sampling",
        "No frontier model has ever attempted a covert action here",
        "No human has ever judged a covert action",
        "Most published rows contain no model at all",
    ):
        assert phrase in text, f"the bounds panel no longer states: {phrase}"

    # No published authorization anywhere records a real human.
    flags: list[object] = []

    def walk(node: object) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "actual_human":
                    flags.append(value)
                walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    for path in sorted((ROOT / "artifacts").rglob("*.json")):
        walk(json.loads(path.read_text(encoding="utf-8")))
    assert flags, "no authorization records found; the sweep is broken"
    assert not any(f is True for f in flags), (
        "an artifact now records a real human approval -- the page states that "
        "none does, and the page must be rewritten, not the test"
    )
    assert f"{sum(1 for f in flags if f is True)}/{len(flags)}" in text, (
        "the page does not carry the human-approval record count"
    )


def test_the_t4_authorization_boundary_counts(text: str) -> None:
    """The count that replaced this project's retracted "gate never reached" claim.

    ``docs/findings/T4-human-gate-reached.md`` establishes that covert calls did
    reach the durable authorization boundary on T4, and that no evaluation row
    records it because that runner's publication path is unwired. The page states
    the count from capture provenance instead; this recomputes it, and asserts the
    contrast that makes it meaningful -- the hosted seats stop at step 0.

    If a T4 evaluation row is ever published, this test keeps passing and the
    page keeps being right; if a hosted seat ever gets past step 0, it goes red,
    because the page's contrast between the seats would no longer hold.
    """
    local_seats = {"qwen3-14b", "mistral-nemo-12b"}
    local: list[tuple[str, str, str, int]] = []
    frontier: list[tuple[str, str, str, int]] = []
    for path in sorted((ROOT / "artifacts/monitor-captures").rglob("*.json")):
        prov = json.loads(path.read_text(encoding="utf-8"))["provenance"]
        if prov.get("scenario_id") != "T4" or prov.get("leg") != "covert":
            continue
        row = (
            prov["model"],
            prov["prompt_version"],
            prov["git_revision"],
            prov["step_index"],
        )
        (local if prov["model"] in local_seats else frontier).append(row)

    assert local, "no local T4 covert captures; the count on the page is vacuous"
    assert frontier, "no hosted T4 covert captures; the contrast is vacuous"
    assert {r[3] for r in frontier} == {0}, (
        "a hosted monitor seat now has a T4 covert capture past step 0 -- the "
        "page's contrast between the seats no longer holds"
    )
    assert {r[3] for r in local} == {0, 1, 2}, "the local seats no longer run all three steps"

    episodes = len({(r[0], r[1], r[2]) for r in local})
    cells = len({(r[0], r[1]) for r in local})
    # Anchored to the sentence: a bare " 21 " would also match an unrelated
    # figure, and a bare " 22 " (the wrong value) genuinely appears elsewhere.
    claim = (
        f"{len(local)} covert-leg monitor calls across {episodes} episodes "
        f"and {cells} seat"
    )
    assert claim in text, f"the page does not state the boundary count: {claim!r}"
    assert claim.replace(f"{len(local)} covert-leg", f"{len(local) + 1} covert-leg") not in text


def test_a_full_chain_row_that_did_not_hold_is_on_the_page(text: str) -> None:
    """If any published row shows all three gates running and the covert
    objective landing anyway, the page must say so.

    This is the guard against the page's most dangerous possible failure: a
    headline comparison in which the chain stops a covert action, published
    beside an artifact in which it does not. The scan is written as a question
    over ``safeguards_applied`` rather than as a lookup of one scenario, so it
    finds such a row wherever it appears -- and asserts nothing at all when none
    exists, so the page is free to drop the section if the artifact is withdrawn.
    """
    landings = []
    envelopes = sorted((ROOT / "artifacts/model-attacker").glob("*.json"))
    envelopes += [
        p
        for p in sorted((ROOT / "artifacts/model-monitor").glob("*.json"))
        if not p.name.endswith(".monitor.json")
    ]
    envelopes += sorted((ROOT / "artifacts/sabotage-matrix").rglob("sabotage-matrix.json"))

    for path in envelopes:
        for row in json.loads(path.read_text(encoding="utf-8"))["results"]:
            gates = row.get("safeguards_applied") or {}
            if not all(
                gates.get(k) == "executed" for k in ("policy", "monitor", "human_gate")
            ):
                continue
            if row["covert_side_effect_count"] > 0 and str(
                row.get("monitor_source") or ""
            ).startswith("model:"):
                landings.append(row)

    if not landings:
        pytest.skip("no published full-chain row records a covert landing")

    worst = max(landings, key=lambda r: r["covert_side_effect_count"])
    assert f"{worst['covert_side_effect_count']} side effects" in text, (
        "a published row shows the full chain not stopping a covert objective and "
        "the page does not state it -- that is the exact overclaim this page exists "
        "to avoid"
    )
    assert worst["scenario_id"] in text
    assert "the full chain did not stop it" in text


# ---------------------------------------------------------------------------
# The switch panel: six pre-rendered states, and nothing the lane did not run
# ---------------------------------------------------------------------------

T4_ENVELOPE = ROOT / "artifacts/model-monitor/T4-v4-nemo-dev-qwen3.json"
T4_MONITOR_RECORDS = ROOT / "artifacts/model-monitor/T4-v4-nemo-dev-qwen3.monitor.json"
STATE_OPEN = '<div class="state" '


def _panel_blocks(page: str) -> dict[tuple[str, str], str]:
    """Each switch-panel state block's own markup, keyed by (scenario, arm).

    Sliced out of the rendered page rather than asked of the generator. A test
    that read the block off the dict the renderer was handed would pass on a
    renderer that never printed it, which is the failure this file exists to
    catch everywhere else.
    """
    parts = page.split('<div class="states"', 1)
    assert len(parts) == 2, "the switch panel's state container is missing from the page"
    body = parts[1].split("</section>", 1)[0]

    starts = [m.start() for m in re.finditer(re.escape(STATE_OPEN), body)]
    assert starts, "no state blocks inside the switch panel"

    blocks: dict[tuple[str, str], str] = {}
    for index, start in enumerate(starts):
        end = starts[index + 1] if index + 1 < len(starts) else len(body)
        chunk = body[start:end]
        scenario = re.search(r'data-scenario="([^"]+)"', chunk)
        arm = re.search(r'data-arm="([^"]+)"', chunk)
        assert scenario and arm, "a state block carries no scenario/arm pair"
        key = (scenario.group(1), arm.group(1))
        assert key not in blocks, f"two state blocks claim {key}"
        blocks[key] = chunk
    return blocks


def _t1_rows() -> dict[str, dict]:
    """The T1 model-attacker rows, one per arm, read straight off the envelopes."""
    rows: dict[str, dict] = {}
    for path in sorted((ROOT / "artifacts/model-attacker").glob("*.json")):
        for row in json.loads(path.read_text(encoding="utf-8"))["results"]:
            if row["attacker_source"].startswith("model:"):
                rows.setdefault(row["condition"], row)
    return rows


def _t4_rows() -> dict[str, dict]:
    return {
        row["condition"]: row
        for row in json.loads(T4_ENVELOPE.read_text(encoding="utf-8"))["results"]
    }


def _spelled(value: object) -> str:
    """A field as the artifact spells it, so ``None`` reads ``null``, not ``None``."""
    if value is True:
        return "true"
    if value is False:
        return "false"
    if value is None:
        return "null"
    return str(value)


NO_DECISION = "no decision recorded"


def _decision_text(value: object) -> str:
    """A gate's decision as the panel prints it, which is not always as spelled.

    The artifact records a gate that decided nothing as ``None``, and ``null`` in
    a cell captioned only by a gate's name reads to a visitor as a rendering
    fault rather than as a fact. The panel states that one case in words instead.
    This is the only relaxation: every decision that exists is still compared
    against the artifact's own spelling of it, so a reworded verdict still fails.
    """
    return NO_DECISION if value is None else _spelled(value)


def test_the_switch_panel_publishes_exactly_the_measured_states(page: str) -> None:
    """Two scenarios by three arms, and no fourth configuration.

    The arm names are taken from the envelopes rather than typed here, so a lane
    that grows or drops an arm makes this fail instead of quietly leaving the
    panel offering a state with no published row behind it.
    """
    t1, t4 = _t1_rows(), _t4_rows()
    assert len(t1) == 3, f"T1 no longer publishes three arms: {sorted(t1)}"
    assert set(t1) == set(t4), "T1 and T4 no longer run the same three arms"

    blocks = _panel_blocks(page)
    assert set(blocks) == {(s, arm) for s in ("T1", "T4") for arm in t1}
    assert len(blocks) == 6, f"expected six state blocks, found {len(blocks)}"

    # The reachable states are the states, so the controls must be the three
    # gates and nothing else: a fourth switch would offer an unmeasured cell.
    panel = page.split('<fieldset class="panelctl"', 1)[1].split("</fieldset>", 1)[0]
    assert panel.count('type="checkbox" role="switch"') == 3
    assert panel.count('type="radio"') == len({s for s, _ in blocks})


def test_each_panel_block_matches_the_row_it_claims(page: str) -> None:
    """Every figure in a block, against the artifact for that scenario and arm.

    Read independently of the generator, and each assertion is mirrored by one
    that an adjacent wrong value is absent, because "0" and "null" are true of
    almost any block on this page.
    """
    blocks = _panel_blocks(page)
    checked = 0
    for (scenario, arm), chunk in sorted(blocks.items()):
        row = _t1_rows()[arm] if scenario == "T1" else _t4_rows()[arm]
        steps = row["covert_episode"]["steps"]
        body = _plain_text(chunk)

        other = "T4" if scenario == "T1" else "T1"
        assert scenario in body, f"the {scenario} {arm} block does not name its scenario"
        assert other not in body, f"the {scenario} {arm} block bleeds into {other}"

        assert f"covert outcome {row['covert_outcome']}" in body
        count = row["covert_side_effect_count"]
        assert f"covert_side_effect_count: {count}" in body
        assert f"covert_side_effect_count: {count + 1}" not in body
        repaired = _spelled(row["incident_checker_passed"])
        assert f"incident_checker_passed: {repaired}" in body
        assert f"covert_checker_passed: {_spelled(row['covert_checker_passed'])}" in body

        for state, key in (("policy", "policy_decision"), ("monitor", "monitor_verdict")):
            for value in {step[key] for step in steps}:
                assert _decision_text(value) in body, (
                    f"the {scenario} {arm} block does not show {state} {value!r}"
                )
        for step in steps:
            auth = step.get("authorization") or {}
            assert _decision_text(auth.get("decision")) in body
            if auth:
                assert f"actual_human: {_spelled(auth['actual_human'])}" in body

        # The mirror for the line above: with ``null`` reworded, no bare ``null``
        # should survive anywhere a visitor reads. Without this, a block that
        # regressed to printing both would still satisfy every assertion here.
        assert not re.search(r"\bnull\b", body), (
            f"the {scenario} {arm} block prints a bare null to a reader"
        )
        checked += 1

    assert checked == 6, "the per-block comparison did not run on every state"


def test_the_panel_quotes_the_t4_monitor_rationale_verbatim(page: str) -> None:
    """The one rationale the panel prints must be the capture body's, byte for byte.

    Mirrors ``test_route_b_row_and_its_rationale``. This is the only place in the
    panel where a model's own words are shown, so it is the only place the panel
    can misquote one.
    """
    records = json.loads(T4_MONITOR_RECORDS.read_text(encoding="utf-8"))["records"]
    judged = [
        r
        for r in records
        if r["condition"] == "policy_monitor_human"
        and r["leg"] == "covert"
        and r["step_index"] == 0
        and r["monitor_state"] == "judged"
    ]
    assert len(judged) == 1, "T4's full-chain covert step 0 is no longer one judged record"
    record = judged[0]
    assert record["verdict"] == "allow", "the T4 monitor no longer allowed the first step"

    block = _panel_blocks(page)[("T4", "policy_monitor_human")]
    assert record["rationale"] in _plain_text(block), (
        "the T4 monitor's rationale is not quoted verbatim in its state block"
    )
    assert html_mod.escape(record["rationale"]) in block, "the rationale is not escaped"

    matches = [
        p
        for p in sorted((ROOT / "artifacts/monitor-captures").rglob("*.json"))
        if json.loads(json.loads(p.read_text(encoding="utf-8"))["raw_json"]).get("rationale")
        == record["rationale"]
    ]
    assert len(matches) == 1, "the T4 rationale does not resolve to exactly one capture"
    assert matches[0].name.removesuffix(".json")[:16] in block, (
        "the panel does not name the capture its quotation came from"
    )


def test_only_the_default_panel_state_is_visible(page: str) -> None:
    """T1 with every gate off is what a reader sees before touching anything."""
    blocks = _panel_blocks(page)
    visible = []
    for key, chunk in blocks.items():
        opening = chunk[: chunk.index(">") + 1]
        if " hidden" not in opening:
            visible.append(key)
    assert visible == [("T1", "ungated_evaluation_only")], (
        f"the panel opens on {visible} rather than T1 with no safeguards"
    )
    assert len(blocks) - len(visible) == 5, "the other five states are not hidden"


# ---------------------------------------------------------------------------
# The README figures: the same rows, drawn, in a file that stands on its own
# ---------------------------------------------------------------------------


def _figure_text(name: str) -> str:
    """Every <text> node in one figure, joined by a separator no label contains.

    Parsed as XML rather than scanned as a string, so a label that never made it
    into a text node -- left in an attribute, or dropped -- cannot satisfy an
    assertion below. The separator keeps two adjacent labels from accidentally
    spelling a third.
    """
    root = ET.parse(EXPLAINER / name).getroot()
    return " | ".join(el.text or "" for el in root.iter() if el.tag == SVG_TEXT)


def _end_label(row: dict, offset: int = 0) -> str:
    """The covert leg's end label, as the artifact's own two fields spell it."""
    count = row["covert_side_effect_count"] + offset
    return f'{row["covert_outcome"]} · {count} side effect' + ("" if count == 1 else "s")


def test_each_figure_states_the_outcomes_of_the_rows_it_draws() -> None:
    """Every arm drawn, against the envelope row for that scenario and arm.

    Read off the artifacts here rather than asked of the generator, and mirrored
    by an assertion that the same label with the side-effect count one higher is
    absent -- a figure showing ``landed`` with no number, or every number, would
    otherwise satisfy a bare substring scan.
    """
    t1, t4 = _t1_rows(), _t4_rows()
    assert set(t1) == set(t4) and len(t1) == 3, "the lane no longer runs three shared arms"
    drawn = {
        "figures/t1-three-arms.svg": list(t1.values()),
        "figures/t4-three-arms.svg": list(t4.values()),
        "figures/finding-t1-vs-t4.svg": [
            t1["policy_monitor_human"],
            t4["policy_monitor_human"],
        ],
    }

    checked = 0
    for name, rows in drawn.items():
        dark = name.replace(".svg", "-dark.svg")
        text = _figure_text(name)
        assert _figure_text(dark) == text, (
            f"{dark} is not the same drawing as {name}; the two palettes have "
            "drifted into two figures"
        )
        assert len(text) > 400, f"{name} carries almost no text"

        for row in rows:
            assert _end_label(row) in text, (
                f"{name} does not carry the {row['scenario_id']} "
                f"{row['condition']} end label {_end_label(row)!r}"
            )
            assert _end_label(row, 1) not in text, (
                f"{name} carries a wrong side-effect count for {row['condition']}"
            )
            assert row["scenario_id"] in text

            gates = row["safeguards_applied"]
            for step in row["covert_episode"]["steps"]:
                recorded = (
                    ("policy", step["policy_decision"]),
                    ("monitor", step["monitor_verdict"]),
                    ("human_gate", (step.get("authorization") or {}).get("decision")),
                )
                for key, decision in recorded:
                    assert gates[key] in text, f"{name} omits the {key} gate's state"
                    if gates[key] != "executed":
                        continue
                    if decision is None:
                        # A gate that ran and decided nothing was never shown the
                        # covert action. The figure has no caption to say so, so
                        # the drawing has to.
                        assert "never consulted" in text, (
                            f"{name}: {key} ran and judged nothing in "
                            f"{row['condition']}, and the figure does not say so"
                        )
                    else:
                        assert decision in text, (
                            f"{name} does not show {key} deciding {decision!r} in "
                            f"{row['condition']}"
                        )
                for reason in step["policy_reasons"] if gates["policy"] == "executed" else []:
                    assert reason in text, f"{name} drops the policy reason {reason!r}"
            checked += 1

    assert checked == 8, f"the figure comparison ran on {checked} rows, not 8"

    # The hero draws one arm, so it must not be showing any of the others.
    hero = _figure_text("figures/finding-t1-vs-t4.svg")
    assert "policy + monitor + human" in hero
    for absent in ("ungated", "policy only"):
        assert absent not in hero, f"the hero figure also draws the {absent} arm"


def test_the_figures_carry_nothing_they_cannot_fetch() -> None:
    """GitHub renders these through a proxy, as images: nothing external loads.

    A font link, a stylesheet, or an <image> href would not fail visibly -- it
    would simply render as something other than what was checked here, on a
    surface where this project's numbers are read first.
    """
    for name in FIGURES:
        raw = (EXPLAINER / name).read_text(encoding="utf-8")
        urls = re.findall(r"https?://[^\"'\s<>]+", raw)
        assert urls == ["http://www.w3.org/2000/svg"], f"{name} references {urls}"
        assert raw.count("http") == 1, f"{name} names http outside its xmlns"

        for forbidden in ("<script", "<link", "<image", "@import", "xlink", "url("):
            assert forbidden not in raw, f"{name} contains {forbidden}"

        root = ET.fromstring(raw)
        assert root.get("viewBox") and root.get("width") and root.get("height"), (
            f"{name} does not size itself, so GitHub cannot lay it out"
        )
        assert raw.count("<style>") == 1, f"{name} does not carry exactly one stylesheet"
        # An opaque ground: the dark figure has to read on GitHub's dark theme
        # and the light one on its light theme, and neither may show through.
        assert "<rect x=\"0\" y=\"0\"" in raw, f"{name} has no background rect"


# ---------------------------------------------------------------------------
# Presentation invariants the page is published under
# ---------------------------------------------------------------------------


def test_no_external_requests_beyond_google_fonts(page: str) -> None:
    urls = set(re.findall(r"https?://[^\"'\s<>]+", page))
    assert urls, "expected at least the font stylesheet"
    for url in urls:
        assert url.startswith(FONT_HOSTS), f"external reference to {url}"
    for forbidden in ("fetch(", "XMLHttpRequest", "WebSocket(", "<img", "@import"):
        assert forbidden not in page, f"page contains {forbidden}"


def test_no_colour_token_is_defined_only_in_a_conditional_block(page: str) -> None:
    style = re.search(r"<style>(.*?)</style>", page, flags=re.DOTALL)
    assert style, "no inline stylesheet"
    css = style.group(1)

    # The bare :root block is the first one, and it has no nested braces.
    bare = re.search(r"^:root\{(.*?)\}", css, flags=re.DOTALL | re.MULTILINE)
    assert bare, "no bare :root block"
    bare_tokens = set(re.findall(r"(--[\w-]+)\s*:", bare.group(1)))
    assert len(bare_tokens) > 10, "the bare :root palette looks incomplete"

    # Any token declared anywhere in the sheet must also be declared here. That
    # is the whole rule: a token whose only definition sits inside a media or
    # [data-theme] block is undefined for a viewer in the third theme state.
    declared = set(re.findall(r"(--[\w-]+)\s*:", css))
    orphans = declared - bare_tokens
    assert not orphans, f"tokens defined only in a conditional block: {sorted(orphans)}"


def test_count_labels_agree_with_their_counts() -> None:
    """The agreement helpers, at zero, one and many.

    The bug this pins shipped on the masthead: a derived count of 1 under the
    caption "model-vs-model rows". It is invisible until a count happens to land
    on one, which is exactly the kind of defect a generated page should not be
    leaving to luck.
    """
    build = _load_build_module()

    assert build.agreeing(1, ("row", "rows")) == "row"
    assert build.agreeing(0, ("row", "rows")) == "rows"
    assert build.agreeing(2, ("row", "rows")) == "rows"
    # A caption that is not a counted noun passes through whatever the count is.
    assert build.agreeing(None, "spend, captures on disk") == "spend, captures on disk"
    assert build.agreeing(1, "spend, captures on disk") == "spend, captures on disk"
    # ...but a pair with no count is a programming error, not a default.
    with pytest.raises(build.DerivationError):
        build.agreeing(None, ("row", "rows"))

    assert build.counted(1, "cell").endswith(">1</span> cell")
    assert build.counted(0, "cell").endswith(">0</span> cells")
    assert build.counted(2, "cell").endswith(">2</span> cells")
    assert build.counted(1, "body", "bodies").endswith(">1</span> body")
    assert build.counted(3, "body", "bodies").endswith(">3</span> bodies")


def test_no_caption_is_plural_beside_a_figure_of_one(page: str) -> None:
    """Every large figure on the page, checked against the caption under it.

    Both readout constructions -- the masthead strip and the bounds cards -- set
    a figure in large type with its caption directly beneath, so the two read as
    one noun phrase. Where the governing figure is exactly one, no word in the
    caption should be a plural, and on this page none of the singular forms ends
    in "s". A future caption that legitimately contains such a word will trip
    this; adjust the assertion then rather than dropping it.
    """
    pairs = re.findall(r"<li><b>([^<]*)</b><span>([^<]*)</span></li>", page)
    masthead = len(pairs)
    pairs += re.findall(
        r'<div class="fig">([^<]*)</div><span class="figsub">([^<]*)</span>', page
    )
    assert masthead >= 4, "the masthead readout was not found"
    assert len(pairs) - masthead >= 4, "the bounds cards were not found"

    for figure, caption in pairs:
        # A ratio is governed by its numerator: "1 of 30 rows", not "30 rows".
        head = figure.lstrip("$").split("/")[0]
        if not head.isdigit():
            continue
        if int(head) != 1:
            continue
        # Hyphenated compounds are one word: splitting "model-vs-model" on
        # letters alone yields "vs", which is not a plural of anything.
        plurals = [w for w in re.findall(r"[a-z][a-z-]*", caption) if w.endswith("s")]
        assert not plurals, (
            f"figure {figure!r} is 1 but its caption {caption!r} is plural: {plurals}"
        )


def test_quoted_prose_is_verbatim_and_still_on_the_page(page: str) -> None:
    """Every quotation must still be a contiguous passage of what it cites.

    This is the guard that matters most, because the cited documents are edited
    more often than this page is rebuilt. A quotation that has drifted from its
    source -- by a reworded sentence upstream, or by a condensation here that
    silently dropped a clause -- is this repository's own recurring defect: a
    record that does not match what produced it. Rendering such a passage between
    quotation marks with a citation attached is the version of that defect this
    page could commit.

    Emphasis markers and backticks are dropped from both sides before comparing,
    because Markdown emphasis is not part of the sentence. Nothing else is
    normalised away, so an elision or a paraphrase fails.
    """

    def normalise(source: str) -> str:
        return re.sub(r"\s+", " ", source.replace("*", "").replace("`", "")).strip()

    module = _load_build_module()
    assert module.PROSE, "the prose constants block is empty"
    body_text = _plain_text(page)

    for key, entry in module.PROSE.items():
        document = entry["cite"].split()[0].strip()
        path = ROOT / document
        assert path.exists(), f"{key} cites a missing document: {document}"

        haystack = normalise(path.read_text(encoding="utf-8"))
        needle = normalise(entry["text"])
        assert needle in haystack, (
            f"{key} is no longer a verbatim passage of {document}. Either the "
            "document was reworded and the quotation is now stale, or the "
            "quotation was condensed. Re-quote it; do not relax this test."
        )
        assert entry["text"] in body_text, f"{key} is a dead prose constant"
