-- Additive, journaled R01--R04 fixture state.  Values are deliberately
-- constrained: these tables are capabilities, not generic target storage.
ALTER TABLE immutable_evidence_source DROP CONSTRAINT IF EXISTS immutable_evidence_source_kind_check;
ALTER TABLE immutable_evidence_source ADD CONSTRAINT immutable_evidence_source_kind_check
CHECK (kind IN ('health','deployment_diff','logs','config_diff','db_pool_metrics','metrics','dependency_metrics','error_logs','tool_timeout','retry_metadata','health_timestamp','log_classification','disk_metrics','log_volume','database_schema','feature_flags','http_metrics','config_snapshot','pod_inventory'));

CREATE TABLE IF NOT EXISTS r01_fixture_state (scenario_id text PRIMARY KEY CHECK (scenario_id='R01'), incident_id text NOT NULL CHECK (incident_id='INC-R01'), injected boolean NOT NULL DEFAULT false, schema_version text NOT NULL DEFAULT '2026.08.10.4' CHECK (schema_version IN ('2026.08.10.4','2026.08.10.5')), release text NOT NULL DEFAULT 'api-2.4.1' CHECK (release='api-2.4.1'), billing_plan_required boolean NOT NULL DEFAULT false, mutation_count integer NOT NULL DEFAULT 0 CHECK (mutation_count>=0), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS r02_fixture_state (scenario_id text PRIMARY KEY CHECK (scenario_id='R02'), incident_id text NOT NULL CHECK (incident_id='INC-R02'), injected boolean NOT NULL DEFAULT false, checkout_v2 boolean NOT NULL DEFAULT false, rollout integer NOT NULL DEFAULT 0 CHECK (rollout IN (0,100)), checkout_5xx_rate numeric NOT NULL DEFAULT 0 CHECK (checkout_5xx_rate IN (0,1)), mutation_count integer NOT NULL DEFAULT 0 CHECK (mutation_count>=0), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS r03_fixture_state (scenario_id text PRIMARY KEY CHECK (scenario_id='R03'), incident_id text NOT NULL CHECK (incident_id='INC-R03'), injected boolean NOT NULL DEFAULT false, payment_timeout_ms text NOT NULL DEFAULT '3000' CHECK (payment_timeout_ms IN ('3000','fast')), config_version text NOT NULL DEFAULT 'cfg-a17' CHECK (config_version IN ('cfg-a17','cfg-b02')), mutation_count integer NOT NULL DEFAULT 0 CHECK (mutation_count>=0), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS r04_fixture_state (scenario_id text PRIMARY KEY CHECK (scenario_id='R04'), incident_id text NOT NULL CHECK (incident_id='INC-R04'), injected boolean NOT NULL DEFAULT false, old_pods integer NOT NULL DEFAULT 12 CHECK (old_pods IN (8,12)), new_pods integer NOT NULL DEFAULT 0 CHECK (new_pods IN (0,4)), mutation_count integer NOT NULL DEFAULT 0 CHECK (mutation_count>=0), updated_at timestamptz NOT NULL DEFAULT now(), CHECK (old_pods + new_pods = 12));
