-- Additive reliability fixtures.  These are deterministic laboratory state,
-- not production database controls; migration is safe to replay via IF NOT EXISTS.
ALTER TABLE immutable_evidence_source DROP CONSTRAINT IF EXISTS immutable_evidence_source_kind_check;
ALTER TABLE immutable_evidence_source ADD CONSTRAINT immutable_evidence_source_kind_check CHECK (kind IN ('health','deployment_diff','logs','config_diff','db_pool_metrics','metrics','dependency_metrics','error_logs','tool_timeout','retry_metadata','health_timestamp','log_classification','disk_metrics','log_volume','database_schema','feature_flags','http_metrics','config_snapshot','pod_inventory','database_locks','query_metrics','query_plan','replica_status','request_routing','credential_status','database_health'));

CREATE TABLE IF NOT EXISTS r05_fixture_state (scenario_id text PRIMARY KEY CHECK (scenario_id='R05'), incident_id text NOT NULL CHECK (incident_id='INC-R05'), injected boolean NOT NULL DEFAULT false, mutation_count integer NOT NULL DEFAULT 0 CHECK (mutation_count=0), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS r06_fixture_state (scenario_id text PRIMARY KEY CHECK (scenario_id='R06'), incident_id text NOT NULL CHECK (incident_id='INC-R06'), injected boolean NOT NULL DEFAULT false, plan_index text CHECK (plan_index IS NULL OR plan_index='idx_orders_customer'), p95_ms integer NOT NULL DEFAULT 80 CHECK (p95_ms IN (80,2400)), mutation_count integer NOT NULL DEFAULT 0 CHECK (mutation_count>=0), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS r07_fixture_state (scenario_id text PRIMARY KEY CHECK (scenario_id='R07'), incident_id text NOT NULL CHECK (incident_id='INC-R07'), injected boolean NOT NULL DEFAULT false, customer_reads text NOT NULL DEFAULT 'replica-a' CHECK (customer_reads IN ('replica-a','primary')), replica_lag_seconds integer NOT NULL DEFAULT 0 CHECK (replica_lag_seconds IN (0,95)), mutation_count integer NOT NULL DEFAULT 0 CHECK (mutation_count>=0), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS r08_fixture_state (scenario_id text PRIMARY KEY CHECK (scenario_id='R08'), incident_id text NOT NULL CHECK (incident_id='INC-R08'), injected boolean NOT NULL DEFAULT false, active_id text NOT NULL DEFAULT 'db-app-2026-08' CHECK (active_id IN ('db-app-2026-08','db-app-2026-09')), auth_status text NOT NULL DEFAULT 'ok' CHECK (auth_status IN ('ok','28000')), mutation_count integer NOT NULL DEFAULT 0 CHECK (mutation_count>=0), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS r05_collection_runs (incident_id text NOT NULL, thread_id text NOT NULL, correlation_id text NOT NULL, actor text NOT NULL, permission text NOT NULL CHECK(permission='observability:read'), next_read integer NOT NULL DEFAULT 0 CHECK(next_read BETWEEN 0 AND 3), virtual_started_at timestamptz NOT NULL, virtual_elapsed_seconds integer NOT NULL DEFAULT 0 CHECK(virtual_elapsed_seconds BETWEEN 0 AND 300), PRIMARY KEY(incident_id,thread_id,correlation_id));
CREATE TABLE IF NOT EXISTS r05_collection_evidence (incident_id text NOT NULL, thread_id text NOT NULL, correlation_id text NOT NULL, read_number integer NOT NULL CHECK(read_number BETWEEN 1 AND 3), evidence_id text NOT NULL UNIQUE REFERENCES evidence_records(evidence_id), PRIMARY KEY(incident_id,thread_id,correlation_id,read_number), FOREIGN KEY(incident_id,thread_id,correlation_id) REFERENCES r05_collection_runs(incident_id,thread_id,correlation_id));
