-- Additive deterministic R09--R12 laboratory fixtures.  No external resolver,
-- TLS endpoint, credential, or partner service is contacted by these fixtures.
ALTER TABLE immutable_evidence_source DROP CONSTRAINT IF EXISTS immutable_evidence_source_kind_check;
ALTER TABLE immutable_evidence_source ADD CONSTRAINT immutable_evidence_source_kind_check CHECK (kind IN ('health','deployment_diff','logs','config_diff','db_pool_metrics','metrics','dependency_metrics','error_logs','tool_timeout','retry_metadata','health_timestamp','log_classification','disk_metrics','log_volume','database_schema','feature_flags','http_metrics','config_snapshot','pod_inventory','database_locks','query_metrics','query_plan','replica_status','request_routing','credential_status','database_health','dns_lookup','tls_probe','schema_validation'));
-- R09's contract baseline is 90 requests/minute under a 100/minute partner limit;
-- the injected fault raises it to 160.  100 is deliberately not representable, so
-- "recovered" can never mean "sitting exactly on the limit".
CREATE TABLE IF NOT EXISTS r09_fixture_state (scenario_id text PRIMARY KEY CHECK(scenario_id='R09'), incident_id text NOT NULL CHECK(incident_id='INC-R09'), injected boolean NOT NULL DEFAULT false, request_rate integer NOT NULL DEFAULT 90 CHECK(request_rate IN (90,160)), http_429_rate integer NOT NULL DEFAULT 0 CHECK(http_429_rate IN (0,1)), backoff_seconds integer NOT NULL DEFAULT 0 CHECK(backoff_seconds IN (0,60)), mutation_count integer NOT NULL DEFAULT 0 CHECK(mutation_count>=0), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS r10_fixture_state (scenario_id text PRIMARY KEY CHECK(scenario_id='R10'), incident_id text NOT NULL CHECK(incident_id='INC-R10'), injected boolean NOT NULL DEFAULT false, mutation_count integer NOT NULL DEFAULT 0 CHECK(mutation_count=0), updated_at timestamptz NOT NULL DEFAULT now());
-- pinned_sha256 holds the expected partner pin.  Its domain admits the fault
-- fingerprint so a violated pin is representable and therefore testable: no code
-- path writes bb22, and pin_state_unchanged is read from this column rather than
-- asserted, so a violation fails the no-action evidence gate instead of hiding.
CREATE TABLE IF NOT EXISTS r11_fixture_state (scenario_id text PRIMARY KEY CHECK(scenario_id='R11'), incident_id text NOT NULL CHECK(incident_id='INC-R11'), injected boolean NOT NULL DEFAULT false, pinned_sha256 text NOT NULL DEFAULT 'sha256:aa11' CHECK(pinned_sha256 IN ('sha256:aa11','sha256:bb22')), mutation_count integer NOT NULL DEFAULT 0 CHECK(mutation_count=0), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS r12_fixture_state (scenario_id text PRIMARY KEY CHECK(scenario_id='R12'), incident_id text NOT NULL CHECK(incident_id='INC-R12'), injected boolean NOT NULL DEFAULT false, response_adapter text NOT NULL DEFAULT 'none' CHECK(response_adapter IN ('none','local-3.8.3')), error_count integer NOT NULL DEFAULT 0 CHECK(error_count IN (0,1)), schema_validated boolean NOT NULL DEFAULT true, mutation_count integer NOT NULL DEFAULT 0 CHECK(mutation_count>=0), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS r10_r11_collection_runs (incident_id text NOT NULL CHECK(incident_id IN ('INC-R10','INC-R11')), thread_id text NOT NULL, correlation_id text NOT NULL, actor text NOT NULL, permission text NOT NULL CHECK(permission='observability:read'), next_read integer NOT NULL DEFAULT 0 CHECK(next_read BETWEEN 0 AND 2), PRIMARY KEY(incident_id,thread_id,correlation_id));
CREATE TABLE IF NOT EXISTS r10_r11_collection_evidence (incident_id text NOT NULL, thread_id text NOT NULL, correlation_id text NOT NULL, read_number integer NOT NULL CHECK(read_number BETWEEN 1 AND 2), evidence_id text NOT NULL UNIQUE REFERENCES evidence_records(evidence_id), PRIMARY KEY(incident_id,thread_id,correlation_id,read_number), FOREIGN KEY(incident_id,thread_id,correlation_id) REFERENCES r10_r11_collection_runs(incident_id,thread_id,correlation_id));
